alias config='/usr/bin/git --git-dir=/home/gabriel/.dotfiles/ --work-tree=/home/gabriel'
alias gcc89="gcc -Wall -ansi -pedantic"
alias venv="source .venv/bin/activate || source venv/bin/activate || echo 'no venv in .venv nor venv'"
alias ci=code
alias .env="set -a; source .env; set +a"
alias :q=exit  # Not sure whether to be proud or ashamed ¬‿¬
alias hh="npx hardhat"
alias _A='cast to-fixed-point 6'
alias _W='cast to-fixed-point 18'
alias pol='inv resolve -c polygon'
alias sep='inv resolve -c sepolia_v3'
alias eth='inv resolve -c mainnet'
alias castpol='cast call --rpc-url $ALCHEMY_URL_POLYGON'
alias castsep='cast call --rpc-url $ALCHEMY_URL_SEPOLIA'
alias casteth='cast call --rpc-url $ALCHEMY_URL_MAINNET'
alias k='kubectl'

workspace() {
    [ -n "$1" ] && [ -d ~/workspace/"$1" ] && cd ~/workspace/"$1" && return
    echo "No existe ~/workspace/$1" >&2
    return 1
}
alias ws=workspace
if [ -d ~/workspace ]; then
 complete -W "$(ls ~/workspace)" workspace
 complete -W "$(ls ~/workspace)" ws
fi

## Invoke autocomplete (automatically generated by invoke)
_complete_invoke() {
    local candidates
    candidates=`invoke --complete -- ${COMP_WORDS[*]}`
    COMPREPLY=( $(compgen -W "${candidates}" -- $2) )
}
complete -F _complete_invoke -o default invoke inv

win() {
    # Find out boot entry with "efibootmgr"
    sudo efibootmgr -n 0001
    read -p "reboot (y): " reboot
    [ "$reboot" = y ] && sudo reboot
}


pomodoro() {
    # Start a timer and notify on completion. Runs on a detached subprocess.
    # $1: time in minutes (default 35 minutes)
    countdown=${1:-35}
    sleeptime=$(( $countdown * 60 ))
    (
      (
        notify-send \
            --app-name=pomodoro \
            --icon=alarm-symbolic \
            "Starting timer for ${countdown}m" && \
        sleep $sleeptime && \
            notify-send \
                --urgency=critical \
                --app-name=pomodoro \
                --icon=alarm-symbolic \
                "${countdown}m timer complete"
      ) & 
    ) &
    echo "Started timer for $countdown minutes."
}


eth_rpc() {
    curl -X POST -H 'Content-type: application/json' "$1" -d '{"jsonrpc": "2.0", "method": "eth_blockNumber", "params": [], "id": 1}'
}
